import time
import logging
from pathlib import Path
from datetime import datetime
from playwright.sync_api import sync_playwright
from base_watcher import BaseWatcher


class FacebookWatcher(BaseWatcher):
    def __init__(self, vault_path: str = 'AI_Employee_Vault', session_path: str = 'facebook_session', interval: int = 120):
        super().__init__(vault_path=vault_path, check_interval=interval)
        self.session_path = Path(session_path)
        self.platform = 'facebook'
        self.keywords = ['sales', 'client', 'opportunity']
        self.logger = logging.getLogger(self.__class__.__name__)

    def check_for_updates(self) -> list:
        """Launch persistent browser headless, check Facebook feed/notifications for unread mentions."""
        updates = []
        
        with sync_playwright() as p:
            browser = p.chromium.launch_persistent_context(
                user_data_dir=str(self.session_path),
                headless=True
            )
            page = browser.pages[0] if browser.pages else browser.new_page()
            
            try:
                # Navigate to Facebook notifications
                page.goto('https://www.facebook.com/notifications', wait_until='networkidle', timeout=30000)
                page.wait_for_timeout(5000)
                
                # Find unread notifications and mentions
                notifications = page.query_selector_all('[role="article"], div[role="article"]')
                
                for notification in notifications:
                    try:
                        text = notification.inner_text().lower()
                        
                        # Check if contains keywords
                        if any(keyword in text for keyword in self.keywords):
                            # Check if unread (look for unread indicators)
                            is_unread = notification.query_selector('[class*="unread"]') or \
                                       notification.query_selector('[data-click*="unread"]') or \
                                       'font-weight: bold' in notification.evaluate('el => el.style.fontWeight')
                            
                            if is_unread or any(keyword in text for keyword in self.keywords):
                                updates.append({
                                    'platform': self.platform,
                                    'content': notification.inner_text().strip(),
                                    'timestamp': datetime.now().isoformat(),
                                    'keywords_found': [k for k in self.keywords if k in text],
                                    'is_unread': is_unread
                                })
                    except Exception as e:
                        self.logger.debug(f"Error processing notification: {e}")
                        continue
                        
            except Exception as e:
                self.logger.error(f"Error checking Facebook: {e}")
            finally:
                browser.close()
        
        return updates

    def create_action_file(self, item: dict) -> Path:
        """Create action file in Needs_Action with frontmatter and suggested actions."""
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        filename = f"FACEBOOK_{timestamp}.md"
        action_file = self.needs_action / filename
        
        # Generate suggested actions based on keywords
        suggested_actions = []
        if 'sales' in item.get('keywords_found', []):
            suggested_actions.append('- Review sales inquiry and respond within 24 hours')
            suggested_actions.append('- Update CRM with lead information')
        if 'client' in item.get('keywords_found', []):
            suggested_actions.append('- Check client account status')
            suggested_actions.append('- Prepare client response or follow-up')
        if 'opportunity' in item.get('keywords_found', []):
            suggested_actions.append('- Evaluate opportunity for qualification')
            suggested_actions.append('- Schedule discovery call if applicable')
        
        if not suggested_actions:
            suggested_actions = ['- Review notification and determine appropriate action']
        
        content = f"""---
type: {item['platform']}
content: |
  {item['content']}
priority: medium
timestamp: {item['timestamp']}
keywords: {', '.join(item.get('keywords_found', []))}
is_unread: {str(item.get('is_unread', False)).lower()}
---

# Facebook Notification Action Required

## Content
{item['content']}

## Suggested Actions
{chr(10).join(suggested_actions)}

## Notes
- Review the notification on Facebook for full context
- Respond appropriately based on business priorities
- Update this file with actions taken in the Notes section below

---
*Generated by FacebookWatcher*
"""
        
        action_file.write_text(content, encoding='utf-8')
        self.logger.info(f"Created action file: {action_file}")
        
        return action_file


if __name__ == '__main__':
    logging.basicConfig(level=logging.INFO)
    watcher = FacebookWatcher()
    watcher.run()
