"""
Intent Analyzer - AI-Powered Intent Detection
Reads dropped TXT files and determines:
1. What action is needed (invoice, email, whatsapp, facebook, odoo)
2. What entities are present (customer, amount, dates, etc.)
3. What information is missing
4. Creates structured task file automatically

Usage:
    python intent_analyzer.py drop_folder/
"""

import os
import json
from pathlib import Path
from datetime import datetime
from dotenv import load_dotenv

# Load environment
load_dotenv()

# Import AI agent (add src to path if needed)
import sys
sys.path.insert(0, str(Path(__file__).parent))
from ai_agent import ai_reasoning, get_model_info

# Configuration
DROP_FOLDER = Path('drop_folder')
NEEDS_ACTION = Path('data/AI_Employee_Vault/Needs_Action')

# Intent categories
INTENT_TYPES = {
    'whatsapp_reply': 'Reply to WhatsApp message',
    'whatsapp_invoice': 'Create invoice from WhatsApp request',
    'email_send': 'Send email',
    'email_reply': 'Reply to email',
    'email_invoice': 'Create invoice from email request',
    'facebook_post': 'Create Facebook post',
    'facebook_reply': 'Reply to Facebook message',
    'linkedin_post': 'Create LinkedIn post',
    'linkedin_reply': 'Reply to LinkedIn message',
    'odoo_invoice': 'Create invoice in Odoo',
    'odoo_customer': 'Create customer in Odoo',
    'bank_payment': 'Record bank payment',
    'general_task': 'General task to review'
}


def analyze_intent(text: str) -> dict:
    """
    Analyze text to determine intent and extract entities.

    Args:
        text: Content from dropped TXT file

    Returns:
        dict with intent, entities, missing_info, confidence
    """

    prompt = f"""
Analyze this business message and determine what action is needed.

MESSAGE:
{text}

⚠️ STRICT FILTER — READ FIRST:
Before classifying, ask: "Did someone EXPLICITLY request a specific action?"

AUTOMATICALLY classify as general_task (informational) if the message is ANY of:
- A one or two word reply (Ok, Thanks, Noted, G, Sure, Lol, Done)
- A greeting or religious phrase (Jazakallah, Walaikum Assalam, Assalamu Alaikum, Ameen)
- A photo, video, voice note, sticker (message contains "Photo", "Video", "0:xx", "Sticker")
- A forwarded YouTube link, news article, or promotional content
- An OTP or verification code
- A message where NO specific action is explicitly requested
- Any message from a group chat about general discussion

ONLY classify as actionable if ALL of these are true:
1. Someone is EXPLICITLY asking for something to be done
2. You have enough information to actually do it
3. It matches one of: invoice creation, email sending, LinkedIn post, explicit WhatsApp reply request

TASK:
1. Determine the PRIMARY action needed (choose from these):
   - whatsapp_reply (reply to WhatsApp message) - ✅ CAN AUTO
   - whatsapp_invoice (create invoice from WhatsApp) - ✅ CAN AUTO
   - email_send (send new email) - ✅ CAN AUTO
   - email_reply (reply to email) - ✅ CAN AUTO
   - email_invoice (create invoice from email) - ✅ CAN AUTO
   - linkedin_post (create LinkedIn post) - ✅ CAN AUTO
   - linkedin_reply (reply to LinkedIn message) - ❌ CANNOT AUTO (needs manual)
   - facebook_post (create Facebook post) - ❌ CANNOT AUTO (needs manual)
   - facebook_reply (reply to Facebook message) - ❌ CANNOT AUTO (needs manual)
   - odoo_invoice (create invoice in Odoo) - ✅ CAN AUTO
   - odoo_customer (create customer in Odoo) - ✅ CAN AUTO
   - bank_payment (record bank payment) - ❌ CANNOT AUTO (needs manual)
   - job_alert (review job posting) - ❌ CANNOT AUTO (informational)
   - newsletter (read newsletter) - ❌ CANNOT AUTO (informational)
   - notification (review notification) - ❌ CANNOT AUTO (informational)
   - general_task (needs human to decide) - ❌ CANNOT AUTO

2. Determine if this is ACTIONABLE or INFORMATIONAL:

**ACTIONABLE TASKS (can_auto_execute: true):**
- whatsapp_reply - We HAVE WhatsApp automation ✅
- email_send - We HAVE Gmail automation ✅
- odoo_invoice - We HAVE Odoo automation ✅
- linkedin_post - We HAVE LinkedIn automation ✅

**INFORMATIONAL TASKS (can_auto_execute: false):**
- linkedin_reply - We DON'T have LinkedIn reply automation ❌
- facebook_post - We DON'T have Facebook automation ❌
- facebook_reply - We DON'T have Facebook automation ❌
- bank_payment - We DON'T have bank automation ❌
- job_alert - Just information, no action needed ❌
- newsletter - Just information, no action needed ❌
- notification - Just information, no action needed ❌

**SIMPLE RULE:** If we have automation for it → actionable. If not → informational.

3. Extract ALL entities present:
   - customer_name: Name of customer/client (REQUIRED for invoices)
   - customer_phone: Phone number
   - customer_email: Email address (REQUIRED for email sending)
   - invoice_number: Invoice # if MENTIONED by customer (OPTIONAL - will be auto-generated by Odoo if not provided)
   - amount: Money amount (as number) (REQUIRED for invoices)
   - currency: USD, PKR, etc.
   - date: Any dates mentioned
   - subject: Email/message subject
   - order_number: Order # if mentioned
   - product_service: What product/service
   - message_content: The actual message/reply to send (for whatsapp_reply, email_send)
   - post_content: The LinkedIn/Facebook post text (for linkedin_post, facebook_post)

IMPORTANT RULES:
- invoice_number is OPTIONAL - if not mentioned by customer, do NOT mark as missing (Odoo will auto-generate)
- For odoo_invoice: Only customer_name and amount are REQUIRED
- For email_send: customer_email is REQUIRED
- For whatsapp_reply: Extract the suggested reply message as message_content
- Do NOT ask user to provide invoice numbers - system generates them automatically
- If task requires manual action (❌ CANNOT AUTO), mark as informational
- **CRITICAL:** If email mentions "invoice", "create invoice", "need invoice", "send invoice" → It's ACTIONABLE (odoo_invoice)
- **CRITICAL:** Job alerts, newsletters, bank statements → INFORMATIONAL (can't auto-execute)

4. Identify what CRITICAL information is MISSING for the action

5. Rate your confidence (0-100%)

6. Create a ONE-LINE SUMMARY for informational items

**SUMMARY RULES:**
- For job alerts: "Job: [position] at [company] - [location]"
- For invoices: "Invoice request: $[amount] for [customer]"
- For notifications: "[type] from [sender]"
- Be specific, not generic!

OUTPUT JSON FORMAT:
{{
    "primary_intent": "action_type",
    "secondary_intent": "another_action or null",
    "entities": {{
        "field": "value" or null
    }},
    "missing_info": ["field1", "field2"],
    "confidence": 0-100,
    "category": "actionable" or "informational",
    "can_auto_execute": true or false,
    "suggested_action": "Brief description of what to do",
    "one_line_summary": "Short summary for informational items",
    "priority": "urgent|high|normal|low",
    "expires_in_days": 7 or null
}}

3. Identify what CRITICAL information is MISSING for the action

4. Rate your confidence (0-100%)

OUTPUT JSON FORMAT:
{{
    "primary_intent": "action_type",
    "secondary_intent": "another_action or null",
    "entities": {{
        "field": "value" or null
    }},
    "missing_info": ["field1", "field2"],
    "confidence": 0-100,
    "suggested_action": "Brief description of what to do",
    "priority": "urgent|high|normal|low"
}}

EXAMPLE 1 (Invoice with number mentioned):
Input: "Customer John called, needs invoice #12345 for $500 sent to abc@example.com"
Output: {{
    "primary_intent": "odoo_invoice",
    "secondary_intent": "email_send",
    "entities": {{
        "customer_name": "John",
        "customer_email": "abc@example.com",
        "invoice_number": "12345",
        "amount": 500
    }},
    "missing_info": [],
    "confidence": 95,
    "suggested_action": "Create invoice #12345 for $500 and email to customer",
    "priority": "normal"
}}

EXAMPLE 2 (Invoice WITHOUT number - most common):
Input: "Customer ABC Corp needs invoice for consulting work, $2500"
Output: {{
    "primary_intent": "odoo_invoice",
    "entities": {{
        "customer_name": "ABC Corp",
        "amount": 2500
    }},
    "missing_info": [],
    "confidence": 90,
    "suggested_action": "Create invoice for ABC Corp (invoice number will be auto-generated by Odoo)",
    "priority": "normal"
}}

EXAMPLE 3 (Email - missing recipient):
Input: "Send email about meeting"
Output: {{
    "primary_intent": "email_send",
    "entities": {{
        "subject": "Meeting"
    }},
    "missing_info": ["customer_email"],
    "confidence": 40,
    "suggested_action": "Send email about meeting (missing recipient email address)",
    "priority": "high"
}}

EXAMPLE 4 (WhatsApp reply with contact name):
Input: "Reply to WhatsApp from \"Sar Dard\" with: Will get back to you shortly"
Output: {{
    "primary_intent": "whatsapp_reply",
    "entities": {{
        "customer_name": "Sar Dard",
        "message_content": "Will get back to you shortly"
    }},
    "missing_info": [],
    "confidence": 95,
    "suggested_action": "Send WhatsApp message to Sar Dard",
    "category": "actionable",
    "can_auto_execute": true,
    "priority": "normal"
}}

EXAMPLE 5 (WhatsApp reply with phone number):
Input: "Reply to WhatsApp from +923001234567: Thanks for the message"
Output: {{
    "primary_intent": "whatsapp_reply",
    "entities": {{
        "customer_phone": "+923001234567",
        "message_content": "Thanks for the message"
    }},
    "missing_info": [],
    "confidence": 95,
    "suggested_action": "Send WhatsApp message to +923001234567",
    "category": "actionable",
    "can_auto_execute": true,
    "priority": "normal"
}}

SELF-VALIDATION RULES (check these before setting can_auto_execute: true):
- odoo_invoice: You MUST have extracted BOTH customer_name AND amount with real values. If either is missing, set can_auto_execute: false and add them to missing_info.
- email_send: You MUST have extracted a real email address. If missing, set can_auto_execute: false.
- whatsapp_reply: You MUST have either a phone number or a customer name AND a specific message to send. If missing, set can_auto_execute: false.
- When in doubt about any field → set can_auto_execute: false
- NEVER set can_auto_execute: true if missing_info is not empty

NOW ANALYZE THIS:
{text}
"""
    
    # Call AI
    result = ai_reasoning(prompt, task_type="general")
    
    if result is None:
        return {
            'primary_intent': 'general_task',
            'entities': {},
            'missing_info': ['all'],
            'confidence': 0,
            'suggested_action': 'AI failed to analyze - human review needed',
            'priority': 'high',
            'error': 'AI analysis failed'
        }
    
    return result


def create_task_file(intent_data: dict, source_text: str, source_file: str) -> Path:
    """
    Create structured task file in Needs_Action folder.
    
    Args:
        intent_data: Output from analyze_intent()
        source_text: Original message text
        source_file: Name of source TXT file
    
    Returns:
        Path to created file
    """
    
    timestamp = datetime.now().strftime('%Y-%m-%d_%H-%M-%S')
    intent_type = intent_data.get('primary_intent', 'general_task')
    
    # Create filename
    filename = f"{intent_type}_{timestamp}.md"
    file_path = NEEDS_ACTION / filename
    
    # Format entities table
    entities = intent_data.get('entities', {})
    entities_table = "| Field | Value | Confidence |\n"
    entities_table += "|-------|-------|------------|\n"
    
    for field, value in entities.items():
        if value is not None:
            # Estimate confidence based on field
            conf = 95 if field in ['invoice_number', 'amount', 'phone'] else 85
            entities_table += f"| {field} | {value} | {conf}% |\n"
    
    # Format missing info
    missing = intent_data.get('missing_info', [])
    missing_section = ""
    if missing:
        missing_section = "\n## ⚠️ Missing Information\n\n"
        missing_section += "\n".join([f"- [ ] {item}" for item in missing])
        missing_section += "\n\n**Human review required to fill in missing details**\n"
    
    # Create markdown content
    content = f"""---
type: {intent_type}
auto_generated: true
source_file: {source_file}
created: {datetime.now().isoformat()}
ai_confidence: {intent_data.get('confidence', 0)}
requires_human_review: {str(len(missing) > 0).lower()}
---

# AI-Generated Task

**Intent:** {intent_data.get('suggested_action', 'Review and decide action')}

**Priority:** {intent_data.get('priority', 'normal').upper()}

**Confidence:** {intent_data.get('confidence', 0)}%

---

## Extracted Entities

{entities_table}

{missing_section}

## Original Message

```
{source_text}
```

---

## Suggested Action

{intent_data.get('suggested_action', 'Human to decide appropriate action')}

---

## Approval Actions

- [ ] Approve (execute suggested action)
- [ ] Edit & Approve (modify details first)
- [ ] Reject (add reason below)
- [ ] Need More Info (specify what's needed)

---

*Auto-generated by Intent Analyzer - AI-Powered*
*Review before approval*
"""
    
    # Ensure directory exists
    NEEDS_ACTION.mkdir(parents=True, exist_ok=True)
    
    # Write file
    file_path.write_text(content, encoding='utf-8')
    
    return file_path


def process_drop_folder():
    """
    Process all TXT files in drop folder.
    """
    print("=" * 60)
    print("  Intent Analyzer - Processing Drop Folder")
    print("=" * 60)
    print()
    
    # Check if drop folder exists
    if not DROP_FOLDER.exists():
        print(f"[INFO] Drop folder not found. Creating: {DROP_FOLDER}")
        DROP_FOLDER.mkdir(parents=True, exist_ok=True)
        print(f"[INFO] Please drop TXT files into: {DROP_FOLDER.absolute()}")
        return
    
    # Get all TXT files
    txt_files = list(DROP_FOLDER.glob('*.txt'))
    
    if not txt_files:
        print(f"[INFO] No TXT files in drop folder")
        print(f"[INFO] Drop files into: {DROP_FOLDER.absolute()}")
        return
    
    print(f"[INFO] Found {len(txt_files)} file(s) to process")
    print()
    
    # Check AI availability
    ai_info = get_model_info()
    if not ai_info['fallback_available']:
        print("[ERROR] No AI model available!")
        print("Configure Groq API in .env or install Ollama")
        return
    
    print(f"[INFO] Using AI: {ai_info['primary']} ({ai_info['model']})")
    print()
    
    # Process each file
    processed = 0
    errors = 0
    
    for txt_file in txt_files:
        try:
            print(f"[PROCESSING] {txt_file.name}...")
            
            # Read file
            text = txt_file.read_text(encoding='utf-8')
            
            if not text.strip():
                print(f"  [SKIP] File is empty")
                continue
            
            # Analyze intent
            print(f"  [AI] Analyzing intent...")
            intent_data = analyze_intent(text)
            
            if 'error' in intent_data:
                print(f"  [ERROR] {intent_data['error']}")
                errors += 1
                continue
            
            print(f"  [AI] Intent: {intent_data.get('primary_intent', 'unknown')}")
            print(f"  [AI] Confidence: {intent_data.get('confidence', 0)}%")
            
            # Create task file
            print(f"  [CREATE] Task file...")
            task_file = create_task_file(intent_data, text, txt_file.name)
            
            print(f"  [SUCCESS] Created: {task_file.name}")
            print(f"  [LOCATION] {task_file.absolute()}")
            
            # Move processed file to archive
            archive_folder = DROP_FOLDER / 'processed'
            archive_folder.mkdir(exist_ok=True)
            txt_file.rename(archive_folder / txt_file.name)
            
            print(f"  [ARCHIVED] Moved to processed/")
            print()
            
            processed += 1
            
        except Exception as e:
            print(f"  [ERROR] {str(e)}")
            errors += 1
            print()
    
    # Summary
    print("=" * 60)
    print("  Processing Complete")
    print("=" * 60)
    print(f"  Processed: {processed} file(s)")
    print(f"  Errors: {errors}")
    print(f"  Output: {NEEDS_ACTION.absolute()}")
    print()
    
    if processed > 0:
        print("[NEXT] Review created tasks in Needs_Action/")
        print("[NEXT] Run: python src/orchestrator.py")


if __name__ == "__main__":
    process_drop_folder()
